name: Push into main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: docker.io
          organization: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          login: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          image_name: devops-vue-project

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

