name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push and Build Docker image
    
      env:
        IMAGE_NAME: devops-vue-project
        PIPELINE_NUMBER: ${{ github.run_number }}
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ env.PIPELINE_NUMBER }} -t ${{ env.IMAGE_NAME }}:latest .
        docker push ${{ env.IMAGE_NAME }}:${{ env.PIPELINE_NUMBER }}
        docker push ${{ env.IMAGE_NAME }}:latest


