name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t devops-vue-project:latest .
      
    - name: Test
      run: docker run devops-vue-project:latest python main.py # Use "main.py" as the entry point
      
  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.VUEPROJECT }}
        password: ${{ secrets.VUEPROJECT }}
      
    - name: Push Docker image to Docker Hub
      run: |
        docker tag devops-vue-project:latest bolasto/devops-vue-project:latest
        docker push bolasto/devops-vue-project:latest
      env:
        DOCKER_CLI_ACI: 1
